### ISSUE TITLE
cubrid.. cubrid..

### ISSUE THREAD

**Issue by dwuthk** [jinahya/cubrid-jdbc-driver-9.2.26.0004#1]
cubrid!?

**Comment by jinahya** [comment]
야근?

**Comment by dwuthk** [comment]
야근 끝나고 집이요 
저 지난 일요일 혼자 강남바닥에서 두분을 기다림.. ...-_-

**Comment by jinahya** [comment]
헐! 재훈전임이 연락 안줬어요? 내가 급하게 사정이 생겨서ㅜㅜ 토요일인가? 못간다고 했는데...

**Comment by jinahya** [comment]
근데 왜 이걸로 채팅하고 있음? 우리?

**Comment by dwuthk** [comment]
ㅋㅋㅋㅋㅋ 
연락은 받았는데 못봤어요 =_= 금주에 보시졍

**Comment by jinahya** [comment]
내가 재훈씨 연락해 보리다.
